import React from 'react';

/**
 * ReportPrintTemplate
 * A standardized, premium printable template for ERP reports.
 * Designed to look world-class on A4 paper with industrial aesthetics.
 */
export default function ReportPrintTemplate({ title, subtitle, date, data, columns, summaryData }) {
  return (
    <div className="p-12 bg-white text-black min-h-screen font-sans print:p-8 relative overflow-hidden">
      {/* Decorative Side Bar (Premium Touch) */}
      <div className="absolute left-0 top-0 bottom-0 w-1.5 bg-black/5 no-print"></div>

      {/* High-Fidelity Header */}
      <div className="flex justify-between items-end border-b-[3px] border-black pb-8 mb-10 relative">
        <div className="flex items-center gap-4">
           <div className="w-12 h-12 bg-black text-white flex items-center justify-center rounded-xl font-black text-xl shadow-lg">NX</div>
           <div>
              <h1 className="text-2xl font-black uppercase tracking-tighter leading-none">NEXUS ERP</h1>
              <p className="text-[9px] font-bold text-slate-500 uppercase tracking-[0.3em] mt-1">Intelligence Systems</p>
           </div>
        </div>
        <div className="text-right">
          <h2 className="text-xl font-black uppercase tracking-tight text-black">{title}</h2>
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mt-1">{subtitle}</p>
          <div className="mt-3 inline-flex items-center gap-2 bg-slate-100 px-3 py-1 rounded-full">
             <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></span>
             <span className="text-[9px] font-black uppercase tracking-tighter">Generated: {date || new Date().toLocaleDateString()}</span>
          </div>
        </div>
      </div>

      {/* Summary Insights Grid */}
      {summaryData && summaryData.length > 0 && (
        <div className="grid grid-cols-3 gap-6 mb-10">
          {summaryData.map((s, i) => (
            <div key={i} className="bg-slate-50 border border-black/10 p-5 rounded-2xl shadow-sm relative overflow-hidden group">
              <div className="absolute top-0 right-0 w-16 h-16 bg-black/5 rounded-full -mr-8 -mt-8"></div>
              <p className="text-[9px] font-black uppercase text-slate-400 tracking-widest mb-2">{s.label}</p>
              <p className="text-2xl font-black tracking-tight text-black">{s.value}</p>
            </div>
          ))}
        </div>
      )}

      {/* Advanced Data Matrix (Table) */}
      <div className="mb-12 shadow-sm rounded-xl overflow-hidden border border-black/10">
        <table className="w-full border-collapse">
          <thead>
            <tr className="bg-slate-900 text-white">
              {columns.map((col, i) => (
                <th key={i} className="px-6 py-4 text-left text-[9px] font-black uppercase tracking-[0.2em] border-r border-white/10 last:border-0">
                  {col.header}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-black/5">
            {data.map((row, rowIndex) => (
              <tr key={rowIndex} className="hover:bg-slate-50 transition-colors">
                {columns.map((col, colIndex) => (
                  <td key={colIndex} className="px-6 py-4 text-[10px] font-bold text-slate-700 border-r border-black/5 last:border-0">
                    {col.render ? col.render(row) : row[col.key]}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Industrial Footer Section */}
      <div className="mt-auto pt-12 border-t-2 border-slate-100 flex justify-between items-center relative">
        <div className="max-w-xs">
          <div className="flex items-center gap-2 mb-2">
             <div className="w-2 h-2 rounded-full bg-black"></div>
             <p className="text-[9px] font-black uppercase tracking-widest">Confidential Document</p>
          </div>
          <p className="text-[8px] text-slate-400 leading-relaxed font-medium">
            This report is generated by the NexusERP Core Intelligence Engine. 
            Unauthorized duplication or distribution is strictly prohibited. 
            Integrity Hash: {Math.random().toString(36).substring(7).toUpperCase()}
          </p>
        </div>
        
        <div className="flex gap-12">
            <div className="text-center w-40">
                <div className="h-0.5 bg-black/10 mb-2"></div>
                <p className="text-[8px] font-black uppercase tracking-widest text-slate-400">System Verified</p>
            </div>
            <div className="text-center w-48">
                <div className="h-0.5 bg-black mb-2"></div>
                <p className="text-[9px] font-black uppercase tracking-widest">Authorized Head</p>
            </div>
        </div>
      </div>

      {/* Print Specific Stylings */}
      <style dangerouslySetInnerHTML={{ __html: `
        @media print {
          body { background: white !important; }
          .no-print { display: none !important; }
          @page { 
            margin: 1.5cm;
            size: A4;
          }
          .shadow-sm, .shadow-lg, .shadow-2xl { shadow: none !important; }
          * { -webkit-print-color-adjust: exact !important; }
        }
      `}} />
    </div>
  );
}
