CREATE TABLE "costing_jobs" (
    "id" TEXT NOT NULL,
    "drawingNo" TEXT NOT NULL,
    "projectName" TEXT,
    "materialName" TEXT NOT NULL,
    "density" DOUBLE PRECISION NOT NULL,
    "items" JSONB NOT NULL,
    "totalArea" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "totalVolume" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "totalWeight" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "totalLineItems" INTEGER NOT NULL DEFAULT 0,
    "sheetLength" DOUBLE PRECISION NOT NULL DEFAULT 900,
    "sheetWidth" DOUBLE PRECISION NOT NULL DEFAULT 600,
    "sheetThickness" DOUBLE PRECISION NOT NULL DEFAULT 8,
    "sheetCostPerSheet" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "baseSheets" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "addonSheets" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "totalSheets" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "utilizationPct" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "wastagePct" DOUBLE PRECISION NOT NULL DEFAULT 0.25,
    "profitPct" DOUBLE PRECISION NOT NULL DEFAULT 0.10,
    "designPct" DOUBLE PRECISION NOT NULL DEFAULT 0.10,
    "holesPct" DOUBLE PRECISION NOT NULL DEFAULT 0.05,
    "rejectionPct" DOUBLE PRECISION NOT NULL DEFAULT 0.03,
    "packagingCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "totalSetCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "costing_jobs_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "costing_jobs_drawingNo_key" ON "costing_jobs"("drawingNo");
